sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: fq+W6LvnT9Lzg3wgaOcpEAWFasqlYnTQy8pcULVujDeKISFSPrIYZieQXDWS19Vw1pwsdPYSA2oLcZD7fvjI6b59lPSfEvOJIxPMRDN7DY/9QWRaRxZe1hCieptC1D7Bv6LM25iiTLljlabX26HKOs80Klad/Tmjiz92+VGCDJqiZ/UkSFfuRx5tTIDuFJ8Q1TGZKmDw6aGPuHjGPGedCy9OXIHLh4mOEOaFc2v8Rfolx1LwpcBzpCHXR8XFgTMouy5zwFQ9rgPxcSvKA+PrOEDu/IgLJxVeEwU34wSJFACkmAREjQeNW3k/e9CWWhBw+A0y6schwcqZrMm2Fp8zoS2VFRMXLFq9wswAYrpQMHu3Axa+m6OLaMrsE29m6txa5y6QJe3biW56M5N6SK3N8SCzlz3c4J7LvzRYvWXp1g5How1210cImSfWsc3wkp86TH9bv0p8HuG6cUQNYtb9lqnVHRbxq4UHJJe0veFsGE4oVPQXGB0Cs03F0nw5xfMMOO64Zs4FtwkFcBR22m352V6OmltC4MNoJYcNuV1utK1mDMaVqs7LbJYUtTTnz1/DKBm/1N4NlMeKRUux+7ogHAyfOsUKptZ+tlIxLtxNoV/2fnPC4oIvjoVFkfpxchANnNYp+OcctSXGw1lw/U9BIkjFEeqTccQM8wIo0iO+x9Y=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Seats-of-the-Mighty-Volume-3_6226
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy